FROM continuumio/miniconda

ENV IPFS_VERSION=v0.4.6 
ENV IPFS_LOGGING "" 
ENV IPFS_DEBUG "" 
ENV IPFS_PATH /data/ipfs 

RUN apt-get update -y && \
    apt-get install -y wget vim sudo

WORKDIR /tmp

RUN pip install --upgrade pip

RUN wget https://dist.ipfs.io/go-ipfs/${IPFS_VERSION}/go-ipfs_${IPFS_VERSION}_linux-amd64.tar.gz 
RUN tar xvfz go-ipfs_${IPFS_VERSION}_linux-amd64.tar.gz
RUN mv go-ipfs/ipfs /usr/local/bin/ipfs

RUN rm -rf /tmp/*

RUN mkdir -p $IPFS_PATH

#RUN useradd -d $IPFS_PATH -u 1000 -U ipfs && chown ipfs:ipfs $IPFS_PATH && chmod 755 $IPFS_PATH
#RUN chown -R ipfs:ipfs /opt/conda

RUN mkdir /app /app/user
WORKDIR /app/user

COPY ./load.py      /app/user
COPY ./scenes.txt   /app/user
COPY ../hyperion-l1u/config.py /app/user
COPY ./start_ipfs   /usr/local/bin

RUN chmod 777 /usr/local/bin/start_ipfs 

RUN pip install boto3 click
RUN pip install ipfsapi

EXPOSE 4001 
EXPOSE 4002/udp 
EXPOSE 5001 
EXPOSE 8080 
 
#USER    ipfs 
VOLUME  $IPFS_PATH

ENTRYPOINT ["/usr/local/bin/start_ipfs"]
CMD []